name: CI

on:
  push:
    branches: [ "dev", "main" ]
  pull_request:
    branches: [ "dev", "main" ]

# Ton projet est dans un sous-dossier :
defaults:
  run:
    working-directory: EcoRideBetaApp

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      APP_ENV: test
      # SQLite = pas de serveur DB à lancer
      DATABASE_URL: "sqlite:///%kernel.project_dir%/var/test.db"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'              # ← important : 8.3 pour PHPUnit 12
          extensions: mbstring, intl, pdo_sqlite
          tools: composer:v2
          coverage: none

      - name: Composer cache
        uses: actions/cache@v4
        with:
          path: ~/.composer/cache/files
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install deps
        run: composer install --no-interaction --prefer-dist

      # ⚠️ on ne copie PAS .env.test → .env.local (inutile/risqué en CI)
      - name: Prepare schema (SQLite)
        run: |
          php bin/console doctrine:schema:drop --env=test --force --full-database || true
          php bin/console doctrine:schema:create --env=test
          php bin/console doctrine:fixtures:load --env=test -n || true

      - name: Run PHPUnit
        run: php bin/phpunit --testdox

      - name: PHPStan
        run: vendor/bin/phpstan analyse src --level=max

      - name: PHP-CS-Fixer (dry-run)
        run: vendor/bin/php-cs-fixer fix --dry-run --diff || true
